### ISSUE TITLE
Having multiple templates starting with fe_ results in messed up HTML

### ISSUE THREAD

**Issue by pwaldhauer** [madeyourday/contao-rocksolid-frontend-helper#21]
Hey!

Version: 1.2.4

We currently have the following setup:

- fe_page
- fe_header
- fe_footer
- fe_offsite

If we enable the Frontend helper the resulting HTML is partially messed up by body tags that appear in the footer (where the fe_footer template is included)

Screenshot (parsed DOM)
![image](https://cloud.githubusercontent.com/assets/432323/24603541/85a86a96-1861-11e7-80aa-93b75f952188.png)

(The script tag seems to be _in_ the body tag, in the non-parsed HTML source the body tag appears two times, the second time without a closing `>`, that's why it's swallowing the script-tag, I guess)

I did some research and I found line 54 in FrontendHelper.php:

`if (substr($template, 0, 3) === 'fe_') {`

If I replace it with

`if ($template  === 'fe_page') {`

everything works as expected, but I don't know what the implications are.

Could someone please take a look?

**Comment by ausi** [comment]
Thanks for reporting this bug. I think we can use the `outputFrontendTemplate` hook instead of the `fe_` check here to fix this issue.

But independent from the frontend helper it is probably better to name your templates differently so that they don’t start with `fe_`, because in Contao all `fe_`-templates are meant for rendering the whole page, not parts of it.

**Comment by ausi** [comment]
Fixed in version 2.0.3.
